---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Provision instance
      ec2:
        key_name: key1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_type: t2.micro
        image: ami-00399ec92321828f5
        vpc_subnet_id: subnet-c38134a8
        instance_tags: {type: web }
        wait: yes
        exact_count: 1
        count_tag: {type: web}
        region: us-east-2
